/*
Roan Mason
03/30/22

Ask the user for the price of an item and if it is on sale or regularly priced. Calculate 
the amount of discount (if any) and calculate the total cost. Display the amount of the 
discount and the total cost in a text area.
*/
package guiexercise2;

import java.text.DecimalFormat;

public class GUIExercise2 extends javax.swing.JFrame {
    double cost = 0;
    double discount = 0;
    double total = 0;
    final double rate = 0.15;
    
    DecimalFormat money = new DecimalFormat("$#,##0.00");
    /**
     * Creates new form GUIExercise2
     */
    public GUIExercise2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDiscountAns = new javax.swing.ButtonGroup();
        jpBackround = new javax.swing.JPanel();
        lblPrompt = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        lblSalePrompt = new javax.swing.JLabel();
        rbDiscountYes = new javax.swing.JRadioButton();
        rbDiscountNo = new javax.swing.JRadioButton();
        btnCalcDiscount = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpOutput = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBackround.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cash Register", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(179, 50, 162))); // NOI18N

        lblPrompt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPrompt.setText("Enter the price of the item:");

        txtCost.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtCost.setText("0");
        txtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostActionPerformed(evt);
            }
        });

        lblSalePrompt.setText("Is the item on sale (15% OFF)?");

        btnDiscountAns.add(rbDiscountYes);
        rbDiscountYes.setText("Yes");
        rbDiscountYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDiscountYesActionPerformed(evt);
            }
        });

        btnDiscountAns.add(rbDiscountNo);
        rbDiscountNo.setText("No");

        btnCalcDiscount.setText("Calculate Discount");
        btnCalcDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcDiscountActionPerformed(evt);
            }
        });

        tpOutput.setEditable(false);
        jScrollPane1.setViewportView(tpOutput);

        javax.swing.GroupLayout jpBackroundLayout = new javax.swing.GroupLayout(jpBackround);
        jpBackround.setLayout(jpBackroundLayout);
        jpBackroundLayout.setHorizontalGroup(
            jpBackroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBackroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBackroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpBackroundLayout.createSequentialGroup()
                        .addComponent(btnCalcDiscount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBackroundLayout.createSequentialGroup()
                        .addComponent(rbDiscountYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDiscountNo))
                    .addComponent(lblSalePrompt)
                    .addGroup(jpBackroundLayout.createSequentialGroup()
                        .addComponent(lblPrompt)
                        .addGap(27, 27, 27)
                        .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBackroundLayout.setVerticalGroup(
            jpBackroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBackroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBackroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrompt)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblSalePrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpBackroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbDiscountNo)
                    .addComponent(rbDiscountYes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpBackroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBackroundLayout.createSequentialGroup()
                        .addComponent(btnCalcDiscount)
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpBackround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jpBackround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostActionPerformed

    private void rbDiscountYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDiscountYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDiscountYesActionPerformed

    private void btnCalcDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcDiscountActionPerformed
        // TODO add your handling code here:
        cost = Double.parseDouble(txtCost.getText());
        discount = 0;
        if (rbDiscountYes.isSelected() == true){
            discount = cost*rate;
        }
        
        total = cost-discount;
        
        tpOutput.setText("Amount of discount: "+money.format(discount)+"\nFinal Price: "+ money.format(total));
    }//GEN-LAST:event_btnCalcDiscountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIExercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIExercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIExercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIExercise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIExercise2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcDiscount;
    private javax.swing.ButtonGroup btnDiscountAns;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpBackround;
    private javax.swing.JLabel lblPrompt;
    private javax.swing.JLabel lblSalePrompt;
    private javax.swing.JRadioButton rbDiscountNo;
    private javax.swing.JRadioButton rbDiscountYes;
    private javax.swing.JTextPane tpOutput;
    private javax.swing.JTextField txtCost;
    // End of variables declaration//GEN-END:variables
}
